"""empty message

Revision ID: 491c23f3e02c
Revises: 
Create Date: 2017-11-02 14:43:21.293402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491c23f3e02c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
